### ISSUE TITLE
Erro module faltante

### ISSUE THREAD

**Issue by ryan-silva** [HenriqueTardivo/xml_to_danfe_dacte#5]
Olá boa tarde, 
Fui testar o projeto com uma nota aqui e está aparecendo o seguinte erro:

"message": "Erro na requisição Error: Cannot find module './timezones/africa.json'\nRequire stack:\n- C:\\Users\\pc\\Desktop\\VSCODEexec\\TESTE API\\xml_to_danfe_dacte\\src\\application\\modules\\pdf_generator\\gammautils\\lib\\timezoneUtils.js

**Comment by HenriqueTardivo** [comment]
Arquivos que faltavam foram adicionados e os demais bugs corrigidos na branch 'stable'
