### ISSUE TITLE
ERROR: TimeZone

### ISSUE THREAD

**Issue by LucasSouza1407** [HenriqueTardivo/xml_to_danfe_dacte#6]
Boa tarde, estou com o mesmo erro do TimeZone, chegou a atualizar sobre esse erro ? peguei a ultima versão disponível.

segue o erro,
"Erro na requisição Error: Cannot find module './timezones/africa.json'\nRequire stack:\n-"

**Comment by HenriqueTardivo** [comment]
Arquivos que faltavam foram adicionados e os demais bugs corrigidos na branch 'stable'
